### ISSUE TITLE
RandomFields was removed from CRAN on 2022-0504

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [James-Thorson/FishStatsUtils#81]
The {RandomFields} package was removed from CRAN on 2022-05-04 because check problems were not corrected. Thus, I cannot easily install {FishStatsUtils} or other dependency packages. I know a work around for myself; but, I am submitting an issue to find a more permanent solution and help users that come across the error message without a solution.

https://github.com/James-Thorson-NOAA/FishStatsUtils/blob/51c7713682ecc8a30ddb3d1f949b7c241451e75b/DESCRIPTION#L25

**Comment by James-Thorson-NOAA** [comment]
Thanks for the update!

I've been able to confirm all of this, i.e,:

1. `RandomFields` is not on CRAN;
2. it interferes with installing FishStatsUtils unless using `remotes::install_github("james-thorson-NOAA/FishStatsUtils", dep=FALSE)`

It has already been removed in the `dev` branch (where I used `renv` to identify and remove unnecessary dependencies).  

@kellijohnson-NOAA Do you think this is sufficiently important that I should merge the `dev` branch into `main`, or do you think the `dep=FALSE` workaround is sufficient for a couple months?

**Comment by James-Thorson-NOAA** [comment]
Actually, I just checked and it seems like the `dep=FALSE` doesn't actually function as work-around.  Is the best work-around just installing it from GitHub prior to installing VAST, or what did you do?

**Comment by kellijohnson-NOAA** [comment]
I tried installing a previous version from CRAN using the save .tar.gz provided from 2019 but this did not work for me because it was incompatible with something on my machine, i.e., I got
```
make: *** [C:/PROGRA~1/R/etc/i386/Makeconf:243: brownresnick.o] Error 1
ERROR: compilation failed for package 'RandomFields'
* removing 'C:/ProgramFiles/R/library/RandomFields
```
Installing from GitHub via
```
remotes::install_github("cran/RandomFields")
```
did work for me.
You could add a remotes call for the RandomFields package maybe in main until you plan on merging in development.

**Comment by James-Thorson-NOAA** [comment]
OK thanks for discussing this!  After considering, I instead just removed `RandomFields` and `RandomFieldsUtils` from the `Imports` section of `Description` ... they were used by a deprecated simulator, and not otherwise necessary.  

I don't plan to increment the semantic version numbering unless you think I need a release number for this fix?  I think most users will just pull the main branch without needing a release number.

I'm closing for now, but please tell me if you try this and encounter some further problem.  and thanks again for flagging it!
